name: dot
description: A library for parsing & creating Graphviz Dot files.
version: 1.0.0
repository: https://github.com/abitofevrything/graphviz
issue_tracker: https://github.com/abitofevrything/graphviz/issues

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  collection: ^1.17.0
  petitparser: ^6.0.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.16.0
